name: Café 40
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7477862439118326
title: Café 40
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#21272e'
    - '#864330'
    - '#be8234'
    - '#ddce89'
  brandStrength: 0.3125
  lightness: 0.19775857753120363
  saturation: 0.6325644317548722
  rhythmicContrast: 0.6979420948773623
purpose: []
